/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Logins;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import com.mysql.jdbc.Driver;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.sql.*;
import static javax.swing.UIManager.getString;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author admin
 */
public class planet extends javax.swing.JFrame {

    /**
     * Creates new form planet
     */
    public planet() {
        initComponents();
        table_update();
    }
    Connection conn;
PreparedStatement pst;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txttp = new javax.swing.JTextField();
        txtpn = new javax.swing.JTextField();
        txtpid = new javax.swing.JTextField();
        txtpm = new javax.swing.JTextField();
        txttyp = new javax.swing.JTextField();
        txtnum = new javax.swing.JTextField();
        txtprev = new javax.swing.JTextField();
        txtpr = new javax.swing.JTextField();
        txtgalid = new javax.swing.JTextField();
        txtnam = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(null);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("planet"));

        jLabel1.setText("Planet ID");

        jLabel2.setText("Planet Name");

        jLabel4.setText("Planet Mass(Kg)");

        jLabel10.setText("Galaxy ID");

        jLabel9.setText("Name of Satellite");

        jLabel8.setText("Type of Satellite");

        jLabel7.setText("Number of Satellite");

        jLabel6.setText("Planet Revolution");

        jLabel5.setText("Planet Rotation");

        jLabel3.setText("Type Of Planet");

        txttyp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttypActionPerformed(evt);
            }
        });

        txtnum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnumActionPerformed(evt);
            }
        });

        txtnam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnamActionPerformed(evt);
            }
        });

        jButton2.setText("ADD");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("EDIT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("DELETE");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("CANCEL");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtpn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                                    .addComponent(txtpid, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txttp, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtprev, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtnum, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtpm, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtpr, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txttyp, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtnam)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtgalid, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)))))))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtpid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtpn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txttp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtpm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtpr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(txtprev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtnum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(40, 40, 40))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txttyp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8)))
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(txtnam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel10))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtgalid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(63, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel3);
        jPanel3.setBounds(10, 10, 290, 620);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Planet ID", "Planet Name", "Planet Mass", "Type of Pl", "Planet Rot", "Planet Revol", "No.of Sat", "Type of Sat", "Name of Sat", "Galaxy ID"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(310, 450, 1050, 210);

        jButton6.setBackground(new java.awt.Color(102, 255, 255));
        jButton6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton6.setText("Click here to view Planet Information");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton6);
        jButton6.setBounds(790, 50, 290, 25);

        jButton7.setBackground(new java.awt.Color(102, 255, 255));
        jButton7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton7.setText("Click here to view Planet Images");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton7);
        jButton7.setBounds(1110, 50, 240, 25);

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Downloads\\Planet-Best-HD-Wallpaper-43981.jpg")); // NOI18N
        jPanel2.add(jLabel11);
        jLabel11.setBounds(-440, 0, 1810, 690);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1385, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 715, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnumActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    String pid=txtpid.getText();
    String pn=txtpn.getText();
    String tp=txttp.getText();
    String pm=txtpm.getText();
    String pr=txtpr.getText();
    String prev=txtprev.getText();
    String num=txtnum.getText();
    String typ=txttyp.getText();
    String nam=txtnam.getText();
    String galid=txtgalid.getText();
   if(pid.isEmpty())
        {
            JOptionPane.showMessageDialog(this,"Planet id field is empty");
        }
        else if(pn.isEmpty())
        {
            JOptionPane.showMessageDialog(this,"Planet Name field is empty");
        }
        else
            if(tp.isEmpty())
            {
                JOptionPane.showMessageDialog(this,"Type of planet field is empty");
            }
         else
            if(pm.isEmpty())
            {
                JOptionPane.showMessageDialog(this,"Planet mass field is empty");
            }
         else
            if(pr.isEmpty())
            {
                JOptionPane.showMessageDialog(this,"Planet Rotation field is empty");
            }
         else
            if(prev.isEmpty())
            {
                JOptionPane.showMessageDialog(this,"Planet Revolution field is empty");
            }
         else
            if(num.isEmpty())
            {
                JOptionPane.showMessageDialog(this,"Number of satellite field is empty");
            }
             else
            if(typ.isEmpty())
            {
                JOptionPane.showMessageDialog(this,"Type of satellite field is empty");
            }
             else
            if(nam.isEmpty())
            {
                JOptionPane.showMessageDialog(this,"Name of satellite field is empty");
            }
            
         else
            if(galid.isEmpty())
            {
                JOptionPane.showMessageDialog(this,"Galaxy ID field is empty");
            }
  else
   try {
       Class.forName("com.mysql.jdbc.Driver");
       conn=DriverManager.getConnection("jdbc:mysql://localhost/vaishali","root","");
              pst=conn.prepareStatement("insert into planet(Pl_ID,Pl_name,Type_of_pl,Pl_mass,Pl_rot,Pl_revol,No_of_sat,Type_of_sat,Name_of_sat,Gal_id)values(?,?,?,?,?,?,?,?,?,?)");
   pst.setString(1,pid);
               pst.setString(2,pn);
               pst.setString(3,tp);
                pst.setString(4,pm);
                pst.setString(5,pr);
                pst.setString(6,prev);
                pst.setString(7,num);
                pst.setString(8,typ);
                 pst.setString(9,nam);
                  pst.setString(10,galid);
               
                pst.executeUpdate();
                JOptionPane.showMessageDialog(this,"Planet added....");
     
               table_update();    //***udate
               txtpid.setText("");
               txtpn.setText("");
               txttp.setText("");
               txtpm.setText("");
               txtpr.setText("");
               txtprev.setText("");
               txtnum.setText("");
               txttyp.setText("");
               txtnam.setText("");
               txtgalid.setText("");
             
    }    catch (ClassNotFoundException ex) {
            Logger.getLogger(planet.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
            Logger.getLogger(galaxy.class.getName()).log(Level.SEVERE, null, ex);
        }
            
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
  Main m = new Main();
        this.hide();
        m.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
 String pid=txtpid.getText();
    String pn=txtpn.getText();
    String tp=txttp.getText();
    String pm=txtpm.getText();
    String pr=txtpr.getText();
    String prev=txtprev.getText();
    String num=txtnum.getText();
    String typ=txttyp.getText();
    String nam=txtnam.getText();
    String galid=txtgalid.getText();
    
   try {
       Class.forName("com.mysql.jdbc.Driver");
       conn=DriverManager.getConnection("jdbc:mysql://localhost/vaishali","root","");
              pst=conn.prepareStatement("update planet set Pl_name=?,Type_of_pl=?,Pl_mass=?,Pl_rot=?,Pl_revol=?,No_of_sat=?,Type_of_sat=?,Name_of_sat=?,Gal_id=? where Pl_id=?");
   pst.setString(10,pid);
               pst.setString(1,pn);
               pst.setString(2,tp);
                pst.setString(3,pm);
                pst.setString(4,pr);
                pst.setString(5,prev);
                pst.setString(6,num);
                pst.setString(7,typ);
                 pst.setString(8,nam);
                  pst.setString(9,galid);
                 
                pst.executeUpdate();
                JOptionPane.showMessageDialog(this,"Planet updated....");
                
               table_update(); 
               
                jButton2.setEnabled(true);//***udate
               txtpid.setText("");
               txtpn.setText("");
               txttp.setText("");
               txtpm.setText("");
               txtpr.setText("");
               txtprev.setText("");
               txtnum.setText("");
               txttyp.setText("");
               txtnam.setText("");
               txtgalid.setText("");
             
    }    catch (ClassNotFoundException ex) {
            Logger.getLogger(planet.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
            Logger.getLogger(galaxy.class.getName()).log(Level.SEVERE, null, ex);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

    
   try {
       String pid=txtpid.getText();
       Class.forName("com.mysql.jdbc.Driver");
       conn=DriverManager.getConnection("jdbc:mysql://localhost/vaishali","root","");
              pst=conn.prepareStatement("Delete from planet where Pl_id=?");
   pst.setString(1,pid);
             
                pst.executeUpdate();
                JOptionPane.showMessageDialog(this,"Planet Deleted....");
              
                table_update();
             
                jButton2.setEnabled(true);//***udate
               txtpid.setText("");
                txtpn.setText("");
               txttp.setText("");
               txtpm.setText("");
               txtpr.setText("");
               txtprev.setText("");
               txtnum.setText("");
               txttyp.setText("");
               txtnam.setText("");
               txtgalid.setText("");
               
               
              
    }    catch (ClassNotFoundException ex) {
            Logger.getLogger(planet.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
            Logger.getLogger(galaxy.class.getName()).log(Level.SEVERE, null, ex);
        }        // TODO add your handling code here:
                                                // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void txtnamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnamActionPerformed

    private void txttypActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttypActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttypActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
DefaultTableModel d1=(DefaultTableModel)jTable1.getModel();
int selectIndex=jTable1.getSelectedRow();
       txtpid.setText(d1.getValueAt(selectIndex,0).toString());
        txtpn.setText(d1.getValueAt(selectIndex,1).toString());
         txttp.setText(d1.getValueAt(selectIndex,2).toString());
          txtpm.setText(d1.getValueAt(selectIndex,3).toString());
           txtpr.setText(d1.getValueAt(selectIndex,4).toString());
            txtprev.setText(d1.getValueAt(selectIndex,5).toString());
             txtnum.setText(d1.getValueAt(selectIndex,6).toString()); 
             txttyp.setText(d1.getValueAt(selectIndex,7).toString());
             txtnam.setText(d1.getValueAt(selectIndex,8).toString());
             txtgalid.setText(d1.getValueAt(selectIndex,9).toString());
             jButton2.setEnabled(false);
                     // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
planinfo pi=new planinfo();
       pi.setVisible(true);    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
 plaimage p=new plaimage();
        p.setVisible(true);    }//GEN-LAST:event_jButton7ActionPerformed
public void table_update()
    {
        int c;
        
        try {
            Class.forName("com.mysql.jdbc.Driver");
            conn = DriverManager.getConnection("jdbc:mysql://localhost/vaishali","root","");
            pst = conn.prepareStatement("select * from planet");
            java.sql.ResultSet rs= pst.executeQuery();
            
            ResultSetMetaData rd = rs.getMetaData();
            c=rd.getColumnCount();
            DefaultTableModel df= (DefaultTableModel)jTable1.getModel();
            df.setRowCount(0);
            
            while(rs.next())
            {
               Vector v2 = new Vector();
                
                for(int i=1; i<=c; i++)
                {
                    v2.add(rs.getString("Pl_id"));
                     v2.add(rs.getString("Pl_name"));
                      v2.add(rs.getString("Type_of_pl"));
                       v2.add(rs.getString("Pl_mass"));
                        v2.add(rs.getString("Pl_rot"));
                         v2.add(rs.getString("Pl_revol"));
                          v2.add(rs.getString("No_of_sat"));
                           v2.add(rs.getString("Type_of_sat"));
                            v2.add(rs.getString("Name_of_sat"));
                             v2.add(rs.getString("Gal_id"));
                             
                }
                df.addRow(v2);
                
                
            }
            
            
            
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(galaxy.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(galaxy.class.getName()).log(Level.SEVERE, null, ex);
        }
             
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(planet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(planet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(planet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(planet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new planet().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtgalid;
    private javax.swing.JTextField txtnam;
    private javax.swing.JTextField txtnum;
    private javax.swing.JTextField txtpid;
    private javax.swing.JTextField txtpm;
    private javax.swing.JTextField txtpn;
    private javax.swing.JTextField txtpr;
    private javax.swing.JTextField txtprev;
    private javax.swing.JTextField txttp;
    private javax.swing.JTextField txttyp;
    // End of variables declaration//GEN-END:variables
}
