/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Logins;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.DriverManager;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import com.mysql.jdbc.Driver;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.sql.*;
import static javax.swing.UIManager.getString;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author admin
 */
public class star extends javax.swing.JFrame {

    /**
     * Creates new form star
     */
    public star() {
        initComponents();
        table_update();
    }
    Connection conn;
PreparedStatement pst;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtst = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtnam = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtmas = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtlum = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtlif = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtcon = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtgalid = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(null);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("star"));

        jLabel1.setText("Star ID");

        jLabel2.setText("Star Name");

        jLabel3.setText("Star Mass");

        jLabel4.setText("Star Luminosity");

        jLabel5.setText("Life Span");

        jLabel6.setText("Consellation");

        jLabel7.setText("Galaxy ID");

        jButton1.setText("ADD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("EDIT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("DELETE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("CANCEL");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(txtmas, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(txtlum, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(txtlif, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65)
                        .addComponent(txtcon, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74)
                        .addComponent(txtst, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(txtnam, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton3))))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton4)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtgalid, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(txtst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtnam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txtmas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txtlum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(txtlif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel6))
                    .addComponent(txtcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel7))
                    .addComponent(txtgalid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addGap(64, 64, 64))
        );

        jPanel2.add(jPanel3);
        jPanel3.setBounds(10, 10, 280, 560);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Star ID", "Star Name", "Star Mass", "Star Luminosity", "Life Span", "Consellation", "Galaxy ID"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jPanel2.add(jScrollPane2);
        jScrollPane2.setBounds(300, 10, 730, 180);

        jButton5.setBackground(new java.awt.Color(255, 255, 51));
        jButton5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton5.setText("Click here to view Star Information");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5);
        jButton5.setBounds(450, 580, 260, 25);

        jButton6.setBackground(new java.awt.Color(255, 255, 51));
        jButton6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton6.setText("Click here to view Star Images");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton6);
        jButton6.setBounds(780, 580, 270, 25);

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Downloads\\star.jpg")); // NOI18N
        jPanel2.add(jLabel8);
        jLabel8.setBounds(-540, -300, 1910, 1090);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1437, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 921, Short.MAX_VALUE)
                .addGap(46, 46, 46))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
String st=txtst.getText();
    String nam=txtnam.getText();
    String mas=txtmas.getText();
    String lum=txtlum.getText();
    String lif=txtlif.getText();
    String con=txtcon.getText();
    String galid=txtgalid.getText();
     if(st.isEmpty())
        {
            JOptionPane.showMessageDialog(this,"Star id field is empty");
        }
        else if(nam.isEmpty())
        {
            JOptionPane.showMessageDialog(this,"Star Name field is empty");
        }
        else
            if(mas.isEmpty())
            {
                JOptionPane.showMessageDialog(this,"Star Mass field is empty");
            }
         else
            if(lum.isEmpty())
            {
                JOptionPane.showMessageDialog(this,"Star Luminosity field is empty");
            }
         else
            if(lif.isEmpty())
            {
                JOptionPane.showMessageDialog(this,"Life span field is empty");
            }
         else
            if(con.isEmpty())
            {
                JOptionPane.showMessageDialog(this,"Consellation field is empty");
            }
         
         else
            if(galid.isEmpty())
            {
                JOptionPane.showMessageDialog(this,"Galaxy ID field is empty");
            }
     else
        
     
    try{

        Class.forName( "com.mysql.jdbc.Driver");
              conn=DriverManager.getConnection("jdbc:mysql://localhost/vaishali","root","");
              pst=conn.prepareStatement("insert into star(Star_id,Star_name,St_mass,St_luminosity,Life_span,Consellation,Gal_id)values(?,?,?,?,?,?,?)");
     pst.setString(1,st);
               pst.setString(2,nam);
               pst.setString(3,mas);
                pst.setString(4,lum);
                pst.setString(5,lif);
                pst.setString(6,con);
                pst.setString(7,galid);
                 
                  
                pst.executeUpdate();
                JOptionPane.showMessageDialog(this,"Star added....");
               table_update();    //***udate
               txtst.setText("");
               txtnam.setText("");
               txtmas.setText("");
               txtlum.setText("");
               txtlif.setText("");
               txtcon.setText("");
               txtgalid.setText("");
              
              }   catch (ClassNotFoundException ex) {
            Logger.getLogger(star.class.getName()).log(Level.SEVERE, null, ex);
        
          
     } catch (SQLException ex) {
            Logger.getLogger(galaxy.class.getName()).log(Level.SEVERE, null, ex);
        }
   
           // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
Main m = new Main();
        this.hide();
        m.setVisible(true);         // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
String st=txtst.getText();
    String nam=txtnam.getText();
    String mas=txtmas.getText();
    String lum=txtlum.getText();
    String lif=txtlif.getText();
    String con=txtcon.getText();
    String galid=txtgalid.getText();
     
    try{

        Class.forName( "com.mysql.jdbc.Driver");
              conn=DriverManager.getConnection("jdbc:mysql://localhost/vaishali","root","");
              pst=conn.prepareStatement("Update star set Star_name=?,St_mass=?,St_luminosity=?,Life_span=?,Consellation=?,Gal_id=? where Star_id=?");
                pst.setString(7,st);
              pst.setString(1,nam);
               pst.setString(2,mas);
                pst.setString(3,lum);
                pst.setString(4,lif);
                pst.setString(5,con);
                pst.setString(6,galid);
                 
                  
                pst.executeUpdate();
                JOptionPane.showMessageDialog(this,"Star updated....");
               table_update();    //***udate
               txtst.setText("");
               txtnam.setText("");
               txtmas.setText("");
               txtlum.setText("");
               txtlif.setText("");
               txtcon.setText("");
               txtgalid.setText("");
              
              }   catch (ClassNotFoundException ex) {
            Logger.getLogger(star.class.getName()).log(Level.SEVERE, null, ex);
        
          
     } catch (SQLException ex) {
            Logger.getLogger(galaxy.class.getName()).log(Level.SEVERE, null, ex);
        }
           // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

    
    try{
        String st=txtst.getText();
        Class.forName( "com.mysql.jdbc.Driver");
              conn=DriverManager.getConnection("jdbc:mysql://localhost/vaishali","root","");
              pst=conn.prepareStatement("Delete from star where Star_id=?");
              
                   pst.setString(1,st);
                pst.executeUpdate();
                JOptionPane.showMessageDialog(this,"Star Deleted....");
               table_update(); 
               jButton1.setEnabled(true);//***udate
               txtst.setText("");
               txtnam.setText("");
               txtmas.setText("");
               txtlum.setText("");
               txtlif.setText("");
               txtcon.setText("");
               txtgalid.setText("");
              
              }   catch (ClassNotFoundException ex) {
            Logger.getLogger(star.class.getName()).log(Level.SEVERE, null, ex);
        
          
     } catch (SQLException ex) {
            Logger.getLogger(galaxy.class.getName()).log(Level.SEVERE, null, ex);
        }
           // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
DefaultTableModel d1=(DefaultTableModel)jTable2.getModel();
int selectIndex=jTable2.getSelectedRow();
       txtst.setText(d1.getValueAt(selectIndex,0).toString());
        txtnam.setText(d1.getValueAt(selectIndex,1).toString());
         txtmas.setText(d1.getValueAt(selectIndex,2).toString());
          txtlum.setText(d1.getValueAt(selectIndex,3).toString());
           txtlif.setText(d1.getValueAt(selectIndex,4).toString());
            txtcon.setText(d1.getValueAt(selectIndex,5).toString());
             txtgalid.setText(d1.getValueAt(selectIndex,6).toString()); 
             
             
        jButton1.setEnabled(false);         // TODO add your handling code here:
    }//GEN-LAST:event_jTable2MouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
starinfo st=new starinfo();
st.setVisible(true);    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
       starimag st=new starimag();
st.setVisible(true); // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed
public void table_update()
    {
        int c;
        
        try {
            Class.forName("com.mysql.jdbc.Driver");
            conn = DriverManager.getConnection("jdbc:mysql://localhost/vaishali","root","");
            pst = conn.prepareStatement("select * from star");
            java.sql.ResultSet rs= pst.executeQuery();
            
            ResultSetMetaData rd = rs.getMetaData();
            c=rd.getColumnCount();
            DefaultTableModel df= (DefaultTableModel)jTable2.getModel();
            df.setRowCount(0);
            
            while(rs.next())
            {
               Vector v2 = new Vector();
                
                for(int i=1; i<=c; i++)
                {
                    v2.add(rs.getString("Star_id"));
                     v2.add(rs.getString("Star_name"));
                      v2.add(rs.getString("St_mass"));
                       v2.add(rs.getString("St_luminosity"));
                        v2.add(rs.getString("Life_span"));
                         v2.add(rs.getString("Consellation"));
                          v2.add(rs.getString("Gal_id"));
                         
                            
                }
                df.addRow(v2);
                
                
            }
            
            
            
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(galaxy.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(galaxy.class.getName()).log(Level.SEVERE, null, ex);
        }
             
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(star.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(star.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(star.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(star.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new star().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField txtcon;
    private javax.swing.JTextField txtgalid;
    private javax.swing.JTextField txtlif;
    private javax.swing.JTextField txtlum;
    private javax.swing.JTextField txtmas;
    private javax.swing.JTextField txtnam;
    private javax.swing.JTextField txtst;
    // End of variables declaration//GEN-END:variables
}
